### ISSUE TITLE
leak_kprocess() return null

### ISSUE THREAD

**Issue by maoxian123** [zer0condition/GDRVLib#2]
uintptr_t gdriver_lib::get_process_base(const char* image_name)
{
	get_eprocess_offsets();

	cr3 = get_system_dirbase();

	if (!cr3)
	{
		printf("cr3 null\n");
		return NULL;

	}

	uintptr_t kprocess_initial = leak_kprocess();
 //kprocess_initial  is null
......
......
}

**Comment by skidofficial** [comment]
load the driver 🤦
